[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib', "node_modules"]
solc= "0.8.20"


[fmt]
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
runs = 100

# See more config options https://github.com/foundry-rs/foundry/tree/master/config